id: P010611
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:26.348672
source_metadata:
  id: bdr:W30191
  title: འདུལ་བའི་གླེང་འབུམ
  author: ''
  volumes:
    d9db6a445c3048f3ae30905ea313daf5:
      image_group_id: I6460
      title: ''
      volume_number: 1
      total_pages: 1128
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
